name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.5 || 3.6 || 3.7 || 3.8
    - name: Run tox
      run: |
        pip install tox
        tox
